name: 'Composite action recipe'
description: 'Greets the user and returns 42'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  anwser:
    description: 'Answer to life, the universe, and everything'
    value: ${{ steps.deep-thought.outputs.answer }}

runs:
  using: "composite"
  steps:
    - name: Awesome bash script
      id: deep-thought
      shell: bash
      run: |
        echo "Hello ${{ inputs.who-to-greet }}."
        echo "answer=42" >> $GITHUB_OUTPUT
        echo "So long, and thanks for all the fish."